// Tracked on purpose. expo-env.d.ts carries this same reference but is
// generated by the CLI and gitignored, so a clean checkout running only
// `tsc --noEmit` would not have it and every `import '@/global.css'` would fail
// to resolve. This file is what makes the typecheck job work without first
// booting Metro.
//
// expo/types is what declares the CSS module shims. The className prop comes
// from nativewind-env.d.ts, which NativeWind's own doctor writes and rewrites,
// so it is left alone rather than merged in here.

/// <reference types="expo/types" />
